set(CPPUNIT_FOUND OFF)

find_path(CPPUNIT_INCLUDE_DIR cppunit/TestCase.h)

find_library(CPPUNIT_LIBRARY NAMES cppunit)

if(CPPUNIT_INCLUDE_DIR AND CPPUNIT_LIBRARY)
	set(CPPUNIT_FOUND ON)
	set(CPPUNIT_LIBRARIES ${CPPUNIT_LIBRARY} ${CMAKE_DL_LIBS})
else(CPPUNIT_INCLUDE_DIR AND CPPUNIT_LIBRARY)
	if(CPPUNIT_FIND_REQUIRED)
		message(FATAL_ERROR "Could not find cppunit")
	else(CPPUNIT_FIND_REQUIRED)
		message(STATUS "Could not find cppunit")
	endif(CPPUNIT_FIND_REQUIRED)
endif(CPPUNIT_INCLUDE_DIR AND CPPUNIT_LIBRARY)
